main:
  - identifier: blog
    name: 블로그
    weight: 999
    params:
      icon:
        vendor: fas
        name: blog

  - name: 링크
    identifier: links
    weight: 1000
    # url: https://github.com/hbstack
    params:
      header: 관련 사이트 링크
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: Documentation
    parent: links
    url: https://hbstack.dev/
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        className: text-primary
      description: The documentation.

  - name: GitHub
    parent: links
    url: https://github.com/hbstack
    weight: 11
    params:
      icon:
        vendor: fab
        name: github
      description: The code repository.

  - name: Discussion
    parent: links
    url: https://github.com/orgs/hbstack/discussions
    weight: 12
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions and share your ideas.

  - name: Bug Report
    parent: links
    url: https://github.com/orgs/hbstack/discussions/new?category=issues-and-bugs
    weight: 13
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Tell us about a bug or issue.

  - name: Feature Request
    parent: links
    url: https://github.com/orgs/hbstack/discussions/new?category=ideas
    weight: 14
    params:
      icon:
        vendor: font-awesome-regular
        name: lightbulb
        color: orange
      description: Suggest new or updated features.
  
  - name: Mastodon
    parent: links
    url: https://techhub.social/@hbstack
    weight: 16
    params:
      icon:
        vendor: simple
        name: mastodon
      description: Follow us on Mastodon to get latest updates.
  
  - name: 플레이스
    identifier: place
    weight: 500
    url: https://naver.me/5AmVd0PR
    params:
      icon:
        vendor: bs
        name: phone  
  - name: 예약
    identifier: reserve
    weight: 499
    url: https://m.booking.naver.com/booking/13/bizes/384022
    params:
      icon:
        vendor: bs
        name: bookmark-star  

# 0507-1362-7787